name: location_macos
description: MacOS implementation of the location plugin
homepage: https://docs.page/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
version: 5.0.0-dev.4

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: location
    platforms:
      macos:
        pluginClass: LocationPlugin
        dartPluginClass: LocationMacOS

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface: ^5.0.0-dev.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
