name: location2_platform_interface
description: A common platform interface for the location plugin.
homepage: https://docs.page/xunreal75/flutterlocation
repository: https://github.com/xunreal75/flutterlocation
version: 6.0.4

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^10.1.4
  very_good_analysis: ^5.0.0+1
