name: location

packages:
  - packages/**

scripts:
  generate:pigeon:
    run: melos exec -- "dart run pigeon --input ./pigeons/messages.dart"
    packageFilters:
      fileExists: "./pigeons/messages.dart"
  test:
    run: melos exec -- "flutter test"
    select-package:
      dir-exists: test

  format:
    run: melos exec -- dart format -o write .

  pubget:
    run: melos exec -- "flutter pub get"

  analyze:
    run: melos exec -- "flutter analyze"