name: location2
description: This library aims at providing you a simple way to get the user location without thinking about permission.
homepage: https://docs.page/Xunreal75/flutterlocation
repository: https://github.com/Xunreal75/flutterlocation
issue_tracker: https://github.com/Xunreal75/flutterlocation/issues?q=is%3Aissue+is%3Aopen
version: 6.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: location2_android
      ios:
        default_package: location2_ios
      # linux:
      #   default_package: location_linux
      macos:
        default_package: location2macos
      web:
        default_package: location2_web
      # windows:
      #   default_package: location_windows

dependencies:
  flutter:
    sdk: flutter
  location2_platform_interface: ^6.0.1
  location2_android: ^6.0.1
  # location_linux:
  #   path: ../location_linux
  location2_macos: ^6.0.1
  location2_ios: ^6.0.1
  location2_web: ^6.0.1
  # location_windows:
  #   path: ../location_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.4
  very_good_analysis: ^5.0.0+1
