name: location2_android
description: Android implementation of the location plugin
homepage: https://docs.page/Xunreal75/flutterlocation
repository: https://github.com/Xunreal75/flutterlocation
version: 6.0.4

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: location2
    platforms:
      android:
        package: app.huth.location
        pluginClass: LocationPlugin
        dartPluginClass: LocationAndroid

dependencies:
  flutter:
    sdk: flutter
  location2_platform_interface: ^6.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^10.1.4
  plugin_platform_interface: ^2.1.4
  very_good_analysis: ^5.0.0+1
