name: tests

on:
  pull_request:
    paths:
      - ".github/workflows/tests.yaml"
      - "src/location_android/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/tests.yaml"
      - "packages/**"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: beta
      - name: Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          flutter pub global activate melos
      - name: Bootstrap melos
        run: melos bs
      - name: Analyze package
        run: melos exec -- flutter analyze --no-fatal-infos

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: beta
      - name: Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          flutter pub global activate melos
      - name: Bootstrap melos
        run: melos bs
      - name: Validate formatting
        run: |
          melos exec -- dart format -o write .
          ./.github/workflows/scripts/validate-formatting.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: beta
      - name: Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          flutter pub global activate melos
      - name: Bootstrap melos
        run: melos bs
      - name: Run tests
        run: melos exec --dir-exists=test -- flutter test
